{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata: { name: tex-pep-secret, namespace: {{ include "tex.namespace" . }} }
type: Opaque
stringData: { apiKey: {{ .Values.apiKey | quote }} }
{{- end }}
