import React, { useState } from "react";
import ComplianceStrip from "./ComplianceStrip.jsx";
import { evaluateCustom } from "../lib/apiClient.js";

/*
  BuyerSurface v9 — for security teams + analyst eyes.

  Two changes from v8:
    1. OWASP ASI 2026 framing leads. EU AI Act is supporting evidence.
    2. "DOWNLOAD A SIGNED EVIDENCE SAMPLE" — runs a real /api/evaluate
       call against a benign sample and gives them a downloadable JSON
       bundle they can forward to legal/audit. Highest-converting
       artifact for this audience.
*/

const SAMPLE_TEXT =
  "Quarterly results announcement: This quarter we are pleased to share strong "
  + "performance across our product lines, with continued investment in research "
  + "and customer success. Full details will be provided through our standard "
  + "investor communications channel. — Generated by Customer Comms AI Agent.";

export default function BuyerSurface({ onClose, onOpenAsi }) {
  const [genState, setGenState] = useState("idle"); // idle | running | error
  const [genErr, setGenErr] = useState("");

  async function generateSample() {
    if (genState === "running") return;
    setGenErr("");
    setGenState("running");
    try {
      const decision = await evaluateCustom({
        content: SAMPLE_TEXT,
        action_type: "outbound_email",
        channel: "email",
        recipient: "investors@yourco.com",
        environment: "production",
      });
      const bundle = {
        tex_evidence_bundle_version: "1.0",
        generated_at: new Date().toISOString(),
        sample_kind: "buyer_walkthrough",
        decision_id: decision.decision_id,
        verdict: decision.verdict,
        confidence: decision.confidence,
        final_score: decision.final_score,
        policy_version: decision.policy_version,
        latency_ms: decision.total_ms,
        evidence: decision.evidence,
        asi_findings: decision.asi_findings,
        router: decision.router,
        deterministic: decision.deterministic,
        semantic: decision.semantic,
        specialists: decision.specialists,
        sample_input: {
          content: SAMPLE_TEXT,
          action_type: "outbound_email",
          channel: "email",
          recipient: "investors@yourco.com",
        },
        framework_alignment: {
          owasp_asi_2026: "every verdict mapped to one or more ASI categories",
          nist_ai_rmf: "evidence supports MAP / MEASURE / MANAGE controls",
          iso_42001: "evidence is auditable per AI MS clauses",
          eu_ai_act: "Article 50 transparency · Aug 2 2026 high-risk obligations",
          finra: "Rule 2210 + 2026 AI-washing examination focus",
          hipaa: "PHI guardrails when configured for clinical workflows",
        },
        _note:
          "This is a real Tex Aegis evidence bundle generated by the live API. "
          + "SHA-256 hash-chained, HMAC-signed, replayable, portable. Forward to "
          + "your auditor or legal team for review.",
      };
      const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `tex-evidence-sample-${decision.decision_id || "buyer"}.json`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      setGenState("idle");
    } catch (e) {
      setGenErr(e.message || "Tex API error");
      setGenState("error");
    }
  }

  return (
    <div style={{
      position: "fixed",
      inset: 0,
      background: "rgba(6, 7, 14, 0.92)",
      backdropFilter: "blur(12px)",
      zIndex: 80,
      overflowY: "auto",
      padding: "32px 16px",
    }}>
      <div className="panel rise" style={{
        maxWidth: 760,
        margin: "0 auto",
        padding: 0,
      }}>
        <div style={{
          padding: "24px 28px 20px",
          borderBottom: "1px solid var(--hairline-2)",
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "space-between",
          gap: 12,
        }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div className="kicker" style={{ color: "var(--yellow)", marginBottom: 6 }}>
              FOR SECURITY TEAMS
            </div>
            <div className="display" style={{ fontSize: 36, lineHeight: 1.05 }}>
              EVERYONE LOGS IT.<br/>
              <span className="glow-yellow" style={{ color: "var(--yellow)" }}>TEX PROVES IT.</span>
            </div>
          </div>
          <button onClick={onClose} className="micro" style={{ color: "var(--ink-faint)", padding: 4 }}>✕ CLOSE</button>
        </div>

        <div style={{ padding: "24px 28px" }}>
          <p style={{ fontSize: 15, color: "var(--ink-dim)", lineHeight: 1.6, marginBottom: 16 }}>
            Tex is the <strong style={{ color: "var(--ink)" }}>OWASP ASI 2026 reference adjudicator</strong>:
            a content-layer adjudication gate for AI agents. Every PERMIT /
            ABSTAIN / FORBID is mapped to specific ASI categories and produces
            a <strong style={{ color: "var(--ink)" }}>SHA-256 hash-chained, HMAC-signed evidence bundle</strong>
            {" "} — the artifact your auditor accepts under EU AI Act, NIST AI RMF, and ISO 42001.
          </p>

          {/* THE EVIDENCE SAMPLE CTA — HIGHEST-CONVERTING ARTIFACT */}
          <div style={{
            padding: "16px 18px",
            border: "1px solid rgba(255, 225, 74, 0.45)",
            borderRadius: 8,
            background: "rgba(255, 225, 74, 0.06)",
            marginBottom: 20,
          }}>
            <div className="kicker" style={{ color: "var(--yellow)", marginBottom: 6 }}>
              ★ SHOW THIS TO YOUR AUDITOR
            </div>
            <div className="display" style={{ fontSize: 18, marginBottom: 6, lineHeight: 1.15 }}>
              DOWNLOAD A SIGNED EVIDENCE SAMPLE
            </div>
            <div style={{ fontSize: 13, color: "var(--ink-dim)", lineHeight: 1.55, marginBottom: 12 }}>
              Hits the live Tex API. Returns a real JSON bundle with verdict,
              confidence, OWASP ASI findings, evidence hash, policy version, and
              framework alignment notes. Forward to legal or audit.
            </div>
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <button
                onClick={generateSample}
                disabled={genState === "running"}
                className="btn-primary"
                style={{ background: "var(--yellow)", color: "#1A1700" }}
              >
                {genState === "running" ? "GENERATING…" : "⬇ GET SAMPLE BUNDLE"}
              </button>
              {genErr && (
                <span className="micro" style={{ color: "var(--red)", alignSelf: "center" }}>
                  {genErr}
                </span>
              )}
            </div>
          </div>

          <div style={{
            padding: "16px 20px",
            background: "var(--bg-2)",
            border: "1px solid var(--hairline-2)",
            borderRadius: 8,
            marginBottom: 20,
          }}>
            <div className="kicker" style={{ color: "var(--cyan)", marginBottom: 10 }}>WHAT TEX DOES</div>
            <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "grid", gap: 10 }}>
              <Bullet text="OWASP ASI 2026 reference adjudicator — every verdict mapped to ASI categories" />
              <Bullet text="Six-layer pipeline: deterministic → retrieval → specialists → semantic → router → evidence" />
              <Bullet text="Three-state verdict (PERMIT / ABSTAIN / FORBID) — never just block/allow" />
              <Bullet text="SHA-256 hash-chained, HMAC-signed evidence — survives offline auditor verification" />
              <Bullet text="Sub-200ms inline adjudication — production-ready latency" />
              <Bullet text="Drop-in API — works with any LLM, any agent framework, any cloud" />
            </ul>
          </div>

          <div className="kicker" style={{ color: "var(--ink-faint)", marginBottom: 8 }}>
            EVIDENCE COVERAGE
          </div>
          <div style={{ marginBottom: 22 }}>
            <ComplianceStrip />
          </div>

          <div style={{
            padding: "16px 20px",
            border: "1px solid rgba(255, 225, 74, 0.3)",
            borderRadius: 8,
            background: "rgba(255, 225, 74, 0.05)",
            marginBottom: 24,
          }}>
            <div className="kicker" style={{ color: "var(--yellow)", marginBottom: 6 }}>WHO BUYS TEX</div>
            <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "grid", gap: 6, color: "var(--ink-dim)", fontSize: 14 }}>
              <li>→ Banks, insurers, hospitals deploying outbound AI to customers</li>
              <li>→ EU AI Act high-risk deployments — Aug 2, 2026 deadline</li>
              <li>→ FINRA-regulated firms preparing for 2026 AI-washing examinations</li>
              <li>→ Healthcare orgs needing PHI guardrails on clinical agents</li>
              <li>→ Any legal team that wants signed logs when an AI causes a lawsuit</li>
            </ul>
          </div>

          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            <a
              href="mailto:matthew@vortexblack.com?subject=Tex%20pilot%20%E2%80%94%2020-min%20walkthrough&body=Hi%20Matt%2C%0A%0AI'd%20like%20to%20see%20Tex%20Aegis%20applied%20to%20our%20agent%20deployment.%0A%0AOrg%3A%20%0AAgent%20use%20case%3A%20%0ARelevant%20frameworks%3A%20EU%20AI%20Act%20%2F%20NIST%20%2F%20ISO%2042001%20%2F%20FINRA%20%2F%20HIPAA%0A"
              className="btn-primary"
            >
              SHOW THIS TO YOUR AUDITOR — 20 MIN
            </a>
            <button onClick={onOpenAsi} className="btn-ghost">
              SEE OWASP ASI MAPPING →
            </button>
            <a
              href="https://texaegis.com"
              target="_blank"
              rel="noreferrer"
              className="micro"
              style={{ color: "var(--ink-faint)", padding: "10px 14px", marginLeft: "auto", alignSelf: "center" }}
            >
              TEXAEGIS.COM →
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

function Bullet({ text }) {
  return (
    <li style={{ display: "flex", gap: 10, fontSize: 13, color: "var(--ink-dim)", lineHeight: 1.5 }}>
      <span style={{ color: "var(--cyan)", flexShrink: 0 }}>▸</span>
      <span>{text}</span>
    </li>
  );
}
