// SPDX-License-Identifier: Apache-2.0
//
// tex-kernel-pep — loads and attaches the cgroup egress hooks (connect4/6,
// sendmsg4/6, sockops), points them at the local enforcement proxy, keeps the
// in-kernel verdict caches warm from the PDP so the hot FORBID set is blocked
// inline in microseconds, and serves the kernel-captured original destination
// to the userspace proxy over a UDS (the keystone the proxy needs to forward
// upstream on PERMIT).
//
// Build: see ../Makefile (clang -target bpf -> tex_redirect.o, then go build).
// Run:   as a privileged DaemonSet container (see ../deploy/daemonset.yaml).
//
// Authored against the fixed PDP contract: GET {PDP}/v1/govern/forbid-set to
// warm the caches; the proxy calls POST {PDP}/v1/govern/decide per request.

package main

import (
	"bufio"
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"log"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target bpf texRedirect ../bpf/tex_redirect.bpf.c

const (
	pinPath       = "/sys/fs/bpf/tex"
	verdictForbid = uint8(2)
)

func env(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// htons/htonl: the eBPF program reads ports/addresses in network byte order.
// htons is its own inverse, so it also converts a stored network-order port
// back to host order on lookup.
func htons(p uint16) uint16 { return (p<<8)&0xff00 | (p>>8)&0x00ff }

func ipToBE(ip net.IP) uint32 {
	v4 := ip.To4()
	if v4 == nil {
		return 0
	}
	// user_ip4 is stored in network byte order (big-endian) as a u32.
	return binary.LittleEndian.Uint32(v4) // bytes already in network order
}

// ip6ToBE packs a 16-byte address into 4 u32 words, each holding network-order
// bytes — mirroring how the kernel stores user_ip6[4]/local_ip6[4].
func ip6ToBE(ip net.IP) [4]uint32 {
	var out [4]uint32
	v6 := ip.To16()
	if v6 == nil {
		return out
	}
	for i := 0; i < 4; i++ {
		out[i] = binary.LittleEndian.Uint32(v6[i*4 : i*4+4])
	}
	return out
}

func u32ToIP4(v uint32) net.IP {
	b := make([]byte, 4)
	binary.LittleEndian.PutUint32(b, v)
	return net.IP(b)
}

func words6ToIP(w [4]uint32) net.IP {
	b := make([]byte, 16)
	for i := 0; i < 4; i++ {
		binary.LittleEndian.PutUint32(b[i*4:], w[i])
	}
	return net.IP(b)
}

// ---- map key/value layouts: mirror the C structs byte-for-byte ----------- //

type dstKey struct {
	IP4  uint32
	Port uint16
	Pad  uint16
}

type dst6Key struct {
	IP6  [4]uint32
	Port uint16
	Pad  uint16
}

type srcKey struct {
	Family  uint8
	Pad     [3]uint8
	SrcIP   [4]uint32
	SrcPort uint16
	Pad2    uint16
}

type origDstVal struct {
	IP     [4]uint32
	Port   uint16
	Family uint8
	Pad    uint8
}

type texConfig struct {
	ProxyIP4     uint32
	ProxyPort    uint16
	UDPProxyPort uint16
	ProxyIP6     [4]uint32
	AllowDNS     uint8
	Pad          [7]uint8
}

func main() {
	cgroupPath := env("TEX_CGROUP", "/sys/fs/cgroup") // governed cgroup root
	proxyAddr := env("TEX_PROXY_ADDR", "127.0.0.1:8088")
	proxy6IP := env("TEX_PROXY6_IP", "::1")
	pdpBase := env("TEX_PDP_BASE", "http://127.0.0.1:8080")
	pdpKey := os.Getenv("TEX_PDP_API_KEY")
	origDstSock := env("TEX_ORIGDST_SOCK", "/run/tex/origdst.sock")

	host, portStr, err := net.SplitHostPort(proxyAddr)
	if err != nil {
		log.Fatalf("bad TEX_PROXY_ADDR %q: %v", proxyAddr, err)
	}
	proxyIP := net.ParseIP(host)
	if proxyIP == nil {
		log.Fatalf("bad proxy ip %q", host)
	}
	var proxyPort uint16
	{
		p, err := strconv.Atoi(portStr)
		if err != nil || p < 1 || p > 65535 {
			log.Fatalf("bad proxy port %q: %v", portStr, err)
		}
		proxyPort = uint16(p)
	}

	proxy6 := net.ParseIP(proxy6IP)
	if proxy6 == nil || proxy6.To16() == nil {
		log.Fatalf("bad TEX_PROXY6_IP %q", proxy6IP)
	}

	// UDP proxy is optional. If no UDP proxy port is set, the sendmsg hooks
	// fail closed (drop) for any non-FORBID UDP datagram — connectionless UDP
	// is never let out unmediated. allow_dns can carve out UDP/53 if the
	// operator accepts the DNS-tunnel residual risk.
	var udpProxyPort uint16
	if v := os.Getenv("TEX_UDP_PROXY_PORT"); v != "" {
		p, err := strconv.Atoi(v)
		if err != nil || p < 1 || p > 65535 {
			log.Fatalf("bad TEX_UDP_PROXY_PORT %q: %v", v, err)
		}
		udpProxyPort = uint16(p)
	}
	var allowDNS uint8
	if v := os.Getenv("TEX_ALLOW_DNS"); v == "1" || v == "true" {
		allowDNS = 1
	}

	// Load the compiled CO-RE objects (generated by bpf2go).
	objs := texRedirectObjects{}
	if err := loadTexRedirectObjects(&objs, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{PinPath: pinPath},
	}); err != nil {
		log.Fatalf("load bpf objects: %v", err)
	}
	defer objs.Close()

	// Configure the redirect targets (network byte order, as the program reads).
	cfg := texConfig{
		ProxyIP4:     ipToBE(proxyIP),
		ProxyPort:    htons(proxyPort),
		UDPProxyPort: htons(udpProxyPort), // htons(0) == 0: stays "no UDP proxy"
		ProxyIP6:     ip6ToBE(proxy6),
		AllowDNS:     allowDNS,
	}
	if err := objs.Config.Put(uint32(0), cfg); err != nil {
		log.Fatalf("write config: %v", err)
	}

	// Attach all egress hooks to the governed cgroup. The loader attaches only
	// under governed workload cgroups; reaching any program == governed.
	type attachSpec struct {
		name   string
		attach ebpf.AttachType
		prog   *ebpf.Program
	}
	specs := []attachSpec{
		{"cgroup/connect4", ebpf.AttachCGroupInet4Connect, objs.TexConnect4},
		{"cgroup/connect6", ebpf.AttachCGroupInet6Connect, objs.TexConnect6},
		{"cgroup/sendmsg4", ebpf.AttachCGroupUDP4Sendmsg, objs.TexSendmsg4},
		{"cgroup/sendmsg6", ebpf.AttachCGroupUDP6Sendmsg, objs.TexSendmsg6},
		{"sockops", ebpf.AttachCGroupSockOps, objs.TexSockOps},
	}
	for _, s := range specs {
		l, err := link.AttachCgroup(link.CgroupOptions{
			Path:    cgroupPath,
			Attach:  s.attach,
			Program: s.prog,
		})
		if err != nil {
			log.Fatalf("attach %s at %s: %v", s.name, cgroupPath, err)
		}
		defer l.Close()
	}

	log.Printf("tex-kernel-pep attached: cgroup=%s redirect->%s (v6 %s) udp_proxy_port=%d allow_dns=%d pdp=%s",
		cgroupPath, proxyAddr, proxy6IP, udpProxyPort, allowDNS, pdpBase)

	// Serve the kernel-captured original destination to the proxy over a UDS.
	go serveOrigDst(origDstSock, objs.SrcToOrig)

	// Warm the in-kernel verdict caches from the PDP on a steady tick. Only
	// high-confidence FORBID destinations are pushed; everything else flows
	// through the redirect to the proxy for the full decision. Absence is
	// never permit.
	ctx := context.Background()
	warm := func() {
		set, err := fetchForbidSet(ctx, pdpBase, pdpKey)
		if err != nil {
			log.Printf("forbid-set refresh failed (cache unchanged): %v", err)
			return
		}
		var n4, n6 int
		for _, d := range set {
			ip := net.ParseIP(d.IP)
			if ip == nil {
				continue
			}
			if v4 := ip.To4(); v4 != nil {
				k := dstKey{IP4: ipToBE(ip), Port: htons(d.Port)}
				_ = objs.VerdictCache.Put(k, verdictForbid)
				n4++
				// A v4 dst may also be reached over a v6 socket as a
				// v4-mapped address; warm that form in the v6 cache too.
				k6 := dst6Key{IP6: ip6ToBE(ip), Port: htons(d.Port)}
				_ = objs.VerdictCache6.Put(k6, verdictForbid)
			} else {
				k6 := dst6Key{IP6: ip6ToBE(ip), Port: htons(d.Port)}
				_ = objs.VerdictCache6.Put(k6, verdictForbid)
				n6++
			}
		}
		log.Printf("verdict caches warmed: %d v4, %d v6 forbid destinations", n4, n6)
	}
	warm()
	ticker := time.NewTicker(30 * time.Second)
	defer ticker.Stop()
	for range ticker.C {
		warm()
	}
}

// ---- UDS server: original-destination lookup for the proxy --------------- //
//
// Contract (T2's client speaks exactly this):
//   request  (newline-terminated JSON): {"src_ip":"<ip>","src_port":<int>,"family":4|6}
//   response (newline-terminated JSON): {"ip":"<orig dst>","port":<int>}
//                                  or:  {"error":"not_found"}

type origDstReq struct {
	SrcIP   string `json:"src_ip"`
	SrcPort int    `json:"src_port"`
	Family  int    `json:"family"`
}

type origDstResp struct {
	IP    string `json:"ip,omitempty"`
	Port  int    `json:"port,omitempty"`
	Error string `json:"error,omitempty"`
}

func serveOrigDst(sockPath string, m *ebpf.Map) {
	if err := os.MkdirAll(filepath.Dir(sockPath), 0o755); err != nil {
		log.Printf("origdst: mkdir %s: %v", filepath.Dir(sockPath), err)
		return
	}
	// Remove a stale socket from a prior run before binding.
	if err := os.Remove(sockPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		log.Printf("origdst: remove stale socket: %v", err)
	}
	ln, err := net.Listen("unix", sockPath)
	if err != nil {
		log.Printf("origdst: listen %s: %v", sockPath, err)
		return
	}
	// The proxy runs as a sidecar; allow it to connect.
	_ = os.Chmod(sockPath, 0o660)
	log.Printf("origdst: serving lookups on %s", sockPath)
	for {
		conn, err := ln.Accept()
		if err != nil {
			log.Printf("origdst: accept: %v", err)
			return
		}
		go handleOrigDst(conn, m)
	}
}

func handleOrigDst(conn net.Conn, m *ebpf.Map) {
	defer conn.Close()
	sc := bufio.NewScanner(conn)
	sc.Buffer(make([]byte, 0, 4096), 64*1024)
	enc := json.NewEncoder(conn)
	for sc.Scan() {
		line := sc.Bytes()
		if len(line) == 0 {
			continue
		}
		var req origDstReq
		if err := json.Unmarshal(line, &req); err != nil {
			_ = enc.Encode(origDstResp{Error: "not_found"})
			continue
		}
		resp := lookupOrigDst(m, req)
		if err := enc.Encode(resp); err != nil {
			return
		}
	}
}

func lookupOrigDst(m *ebpf.Map, req origDstReq) origDstResp {
	if req.SrcPort < 1 || req.SrcPort > 65535 {
		return origDstResp{Error: "not_found"}
	}
	ip := net.ParseIP(req.SrcIP)
	if ip == nil {
		return origDstResp{Error: "not_found"}
	}
	var k srcKey
	k.SrcPort = htons(uint16(req.SrcPort))
	switch req.Family {
	case 6:
		if ip.To16() == nil {
			return origDstResp{Error: "not_found"}
		}
		k.Family = 6
		k.SrcIP = ip6ToBE(ip)
	default: // treat anything else as v4
		if ip.To4() == nil {
			return origDstResp{Error: "not_found"}
		}
		k.Family = 4
		k.SrcIP[0] = ipToBE(ip)
	}

	var val origDstVal
	if err := m.Lookup(&k, &val); err != nil {
		return origDstResp{Error: "not_found"}
	}
	var dstIP net.IP
	if val.Family == 6 {
		dstIP = words6ToIP(val.IP)
	} else {
		dstIP = u32ToIP4(val.IP[0])
	}
	return origDstResp{IP: dstIP.String(), Port: int(htons(val.Port))}
}

type forbidDst struct {
	IP   string `json:"ip"`
	Port uint16 `json:"port"`
}

// fetchForbidSet pulls the hot FORBID destinations the PDP wants blocked
// inline. The endpoint is part of the PDP contract; it returns the
// high-confidence denial set, not the full policy (the full decision stays at
// /v1/govern/decide via the proxy).
func fetchForbidSet(ctx context.Context, base, key string) ([]forbidDst, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, base+"/v1/govern/forbid-set", nil)
	if err != nil {
		return nil, err
	}
	if key != "" {
		req.Header.Set("Authorization", "Bearer "+key)
	}
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, &httpError{resp.StatusCode}
	}
	var out struct {
		Forbid []forbidDst `json:"forbid"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out.Forbid, nil
}

type httpError struct{ code int }

func (e *httpError) Error() string { return "pdp http error" }
