// SPDX-License-Identifier: Apache-2.0
//
// tex-kernel-pep — loads and attaches the cgroup/connect4 redirector, points
// it at the local enforcement proxy, pins the orig-dst map for the proxy to
// read, and keeps the in-kernel verdict cache warm from the PDP so the hot
// FORBID set is blocked inline in microseconds.
//
// Build: see ../Makefile (clang -target bpf -> tex_redirect.o, then go build).
// Run:   as a privileged DaemonSet container (see ../deploy/daemonset.yaml).
//
// Authored against the fixed PDP contract: GET {PDP}/v1/govern/forbid-set to
// warm the cache; the proxy calls POST {PDP}/v1/govern/decide per request.

package main

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"log"
	"net"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target bpf texRedirect ../bpf/tex_redirect.bpf.c

const (
	pinPath       = "/sys/fs/bpf/tex"
	verdictForbid = uint8(2)
)

func env(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

// htons/htonl: the eBPF program reads ports/addresses in network byte order.
func htons(p uint16) uint16 { return (p<<8)&0xff00 | (p>>8)&0x00ff }

func ipToBE(ip net.IP) uint32 {
	v4 := ip.To4()
	if v4 == nil {
		return 0
	}
	// user_ip4 is stored in network byte order (big-endian) as a u32.
	return binary.LittleEndian.Uint32(v4) // bytes already in network order
}

type dstKey struct {
	IP4  uint32
	Port uint16
	Pad  uint16
}

type texConfig struct {
	ProxyIP4  uint32
	ProxyPort uint16
	Pad       uint16
}

func main() {
	cgroupPath := env("TEX_CGROUP", "/sys/fs/cgroup") // governed cgroup root
	proxyAddr := env("TEX_PROXY_ADDR", "127.0.0.1:8088")
	pdpBase := env("TEX_PDP_BASE", "http://127.0.0.1:8080")
	pdpKey := os.Getenv("TEX_PDP_API_KEY")

	host, portStr, err := net.SplitHostPort(proxyAddr)
	if err != nil {
		log.Fatalf("bad TEX_PROXY_ADDR %q: %v", proxyAddr, err)
	}
	proxyIP := net.ParseIP(host)
	if proxyIP == nil {
		log.Fatalf("bad proxy ip %q", host)
	}
	var proxyPort uint16
	{
		p, err := strconv.Atoi(portStr)
		if err != nil || p < 1 || p > 65535 {
			log.Fatalf("bad proxy port %q: %v", portStr, err)
		}
		proxyPort = uint16(p)
	}

	// Load the compiled CO-RE objects (generated by bpf2go).
	objs := texRedirectObjects{}
	if err := loadTexRedirectObjects(&objs, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{PinPath: pinPath},
	}); err != nil {
		log.Fatalf("load bpf objects: %v", err)
	}
	defer objs.Close()

	// Configure the redirect target (network byte order, as the program reads it).
	cfg := texConfig{ProxyIP4: ipToBE(proxyIP), ProxyPort: htons(proxyPort)}
	if err := objs.Config.Put(uint32(0), cfg); err != nil {
		log.Fatalf("write config: %v", err)
	}

	// Attach the connect4 hook to the governed cgroup. The loader attaches
	// only under governed workload cgroups; reaching the program == governed.
	l, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupPath,
		Attach:  ebpf.AttachCGroupInet4Connect,
		Program: objs.TexConnect4,
	})
	if err != nil {
		log.Fatalf("attach cgroup/connect4 at %s: %v", cgroupPath, err)
	}
	defer l.Close()

	log.Printf("tex-kernel-pep attached: cgroup=%s redirect->%s pdp=%s",
		cgroupPath, proxyAddr, pdpBase)

	// Warm the in-kernel verdict cache from the PDP on a steady tick. Only
	// high-confidence FORBID destinations are pushed; everything else flows
	// through the redirect to the proxy for the full decision. Absence is
	// never permit.
	ctx := context.Background()
	warm := func() {
		set, err := fetchForbidSet(ctx, pdpBase, pdpKey)
		if err != nil {
			log.Printf("forbid-set refresh failed (cache unchanged): %v", err)
			return
		}
		for _, d := range set {
			ip := net.ParseIP(d.IP)
			if ip == nil || ip.To4() == nil {
				continue
			}
			k := dstKey{IP4: ipToBE(ip), Port: htons(d.Port)}
			_ = objs.VerdictCache.Put(k, verdictForbid)
		}
		log.Printf("verdict cache warmed: %d forbid destinations", len(set))
	}
	warm()
	ticker := time.NewTicker(30 * time.Second)
	defer ticker.Stop()
	for range ticker.C {
		warm()
	}
}

type forbidDst struct {
	IP   string `json:"ip"`
	Port uint16 `json:"port"`
}

// fetchForbidSet pulls the hot FORBID destinations the PDP wants blocked
// inline. The endpoint is part of the PDP contract; it returns the
// high-confidence denial set, not the full policy (the full decision stays at
// /v1/govern/decide via the proxy).
func fetchForbidSet(ctx context.Context, base, key string) ([]forbidDst, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, base+"/v1/govern/forbid-set", nil)
	if err != nil {
		return nil, err
	}
	if key != "" {
		req.Header.Set("Authorization", "Bearer "+key)
	}
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, &httpError{resp.StatusCode}
	}
	var out struct {
		Forbid []forbidDst `json:"forbid"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out.Forbid, nil
}

type httpError struct{ code int }

func (e *httpError) Error() string { return "pdp http error" }
