"""
ZKPROV integration hook for the ``/v1/guardrail`` evidence path.

When the active decision path generates a model response under a
regulated training-data manifest, this hook produces a
``ProvenanceProof`` (or references a pre-generated one when the
proof was async-generated by the prover side) and attaches a
serialized envelope into the evidence record payload.

Design properties (mirroring ``tex.vet.integration``)
-----------------------------------------------------
*   **Optional / opt-in.** The hook fires only when
    ``TEX_ZKPROV=1`` is set AND the caller explicitly invokes
    ``attach_provenance_proof_to_payload``. Existing callers and
    chains see no behavioral diff.
*   **Fail-open on attach.** Attachment errors never block a
    decision; we log and proceed with an un-proofed payload. A
    cryptographic-availability cliff would be worse than no proof
    at all in the request path.
*   **Fail-closed on verify.** Invalid proofs at audit time are
    flagged. The audit verifier's ``regulator_grade`` flag
    determines whether shim-backed proofs count.
*   **Receipt complement.** When the model emits epistemic claims,
    the receipt (sub-15ms NABAOS-style HMAC) rides alongside the
    ZK proof in the same payload. The receipt is the hot-path
    verification artifact; the proof is the slow-path regulator-
    grade artifact.
"""

from __future__ import annotations

import logging
import os
from typing import Any
from uuid import UUID

from tex.zkprov.commitment import DatasetCommitment, verify_commitment_signature
from tex.zkprov.proof import (
    ProofVerification,
    ProvenanceProof,
    verify_proof,
)
from tex.zkprov.receipts import EpistemicReceipt, verify_receipt


__all__ = [
    "PAYLOAD_KEY_ZKPROV_PROOF",
    "PAYLOAD_KEY_ZKPROV_RECEIPT",
    "PAYLOAD_KEY_ZKPROV_COMMITMENT_ID",
    "TEX_ZKPROV_ENV",
    "is_zkprov_enabled",
    "attach_provenance_proof_to_payload",
    "attach_receipt_to_payload",
    "verify_payload_provenance_proof",
    "verify_payload_receipt",
]


_logger = logging.getLogger(__name__)


# Environment flag (per Thread 14 acceptance criterion 5).
TEX_ZKPROV_ENV = "TEX_ZKPROV"


PAYLOAD_KEY_ZKPROV_PROOF = "zkprov_proof"
PAYLOAD_KEY_ZKPROV_RECEIPT = "zkprov_receipt"
PAYLOAD_KEY_ZKPROV_COMMITMENT_ID = "zkprov_commitment_id"


def is_zkprov_enabled() -> bool:
    """Whether the ZKPROV evidence augmentation is turned on.

    Default: off. Set ``TEX_ZKPROV=1`` to enable.
    """
    value = os.environ.get(TEX_ZKPROV_ENV, "0").strip().lower()
    return value in {"1", "true", "yes", "on"}


def attach_provenance_proof_to_payload(
    payload: dict[str, Any],
    *,
    proof: ProvenanceProof,
    proof_envelope_sha256: str | None = None,
) -> dict[str, Any]:
    """Attach a ProvenanceProof envelope to an evidence payload.

    The proof envelope is serialized as the canonical JSON form
    (see ``ProvenanceProof.to_envelope_json``); the payload also
    carries the commitment ID and envelope SHA-256 at the top
    level so the SCITT transparency view can index without
    parsing the envelope JSON.

    Returns a *copy* of ``payload`` with the new fields. Never
    mutates the input. Fails open on any unexpected error —
    callers that want to fail-closed on attachment should call
    ``serialize`` themselves.
    """
    new_payload = dict(payload)
    try:
        envelope_json = proof.to_envelope_json()
        env_hash = proof_envelope_sha256 or proof.envelope_sha256()
        # We embed the canonical JSON text (not a parsed object) so
        # the evidence-chain hash is byte-stable regardless of
        # downstream JSON re-encoding.
        new_payload[PAYLOAD_KEY_ZKPROV_PROOF] = {
            "envelope_json": envelope_json,
            "envelope_sha256": env_hash,
            "backend": proof.backend.value,
        }
        new_payload[PAYLOAD_KEY_ZKPROV_COMMITMENT_ID] = (
            proof.statement.dataset_commitment_id
        )
    except Exception as exc:  # noqa: BLE001
        _logger.warning(
            "ZKPROV: failed to attach proof to evidence payload (%s); "
            "proceeding without",
            exc,
        )
    return new_payload


def attach_receipt_to_payload(
    payload: dict[str, Any],
    *,
    receipt: EpistemicReceipt,
) -> dict[str, Any]:
    """Attach a NABAOS-style epistemic receipt to the payload.

    Receipt verification is sub-millisecond, so this is the
    hot-path complement to the ZK proof. When both are present in
    the payload, the receipt is what powers interactive
    "did the agent hallucinate" checks; the ZK proof is what
    powers the regulator audit at a later time.
    """
    new_payload = dict(payload)
    try:
        new_payload[PAYLOAD_KEY_ZKPROV_RECEIPT] = receipt.to_envelope_json()
    except Exception as exc:  # noqa: BLE001
        _logger.warning("ZKPROV: failed to attach receipt (%s)", exc)
    return new_payload


def verify_payload_provenance_proof(
    payload: dict[str, Any],
    *,
    expected_dataset_commitment: DatasetCommitment,
    expected_response_sha256_hex: str,
    regulator_grade: bool = False,
) -> ProofVerification | None:
    """Verify a ZKPROV proof embedded in an evidence payload.

    Returns the ``ProofVerification`` result; None when the payload
    has no proof attached. Fail-closed on every error: an unparseable
    proof is treated as failed verification.
    """
    raw = payload.get(PAYLOAD_KEY_ZKPROV_PROOF)
    if not isinstance(raw, dict):
        return None
    envelope_json = raw.get("envelope_json")
    if not isinstance(envelope_json, str):
        return None
    try:
        proof = ProvenanceProof.from_envelope_json(envelope_json)
    except (ValueError, KeyError, RuntimeError) as exc:
        _logger.warning("ZKPROV: failed to parse proof envelope: %s", exc)
        return None
    return verify_proof(
        proof,
        expected_dataset_commitment=expected_dataset_commitment,
        expected_response_sha256_hex=expected_response_sha256_hex,
        regulator_grade=regulator_grade,
    )


def verify_payload_receipt(payload: dict[str, Any]) -> bool:
    """Verify the embedded epistemic receipt's HMAC tag."""
    raw = payload.get(PAYLOAD_KEY_ZKPROV_RECEIPT)
    if not isinstance(raw, str):
        return False
    try:
        import json
        from datetime import datetime
        from tex.zkprov.receipts import (
            EpistemicClaim,
            EpistemicReceipt,
            Pramana,
            ToolCallRecord,
        )

        data = json.loads(raw)
        if data.get("kind") != "tex.zkprov.receipt.v1":
            return False
        receipt = EpistemicReceipt(
            receipt_id=data["receipt_id"],
            response_sha256=data["response_sha256"],
            tool_calls=tuple(
                ToolCallRecord(
                    call_id=c["call_id"],
                    tool_name=c["tool_name"],
                    arguments_sha256=c["arguments_sha256"],
                    result_sha256=c["result_sha256"],
                    occurred_at=datetime.fromisoformat(c["occurred_at"]),
                )
                for c in data["tool_calls"]
            ),
            claims=tuple(
                EpistemicClaim(
                    claim_id=cl["claim_id"],
                    text_sha256=cl["text_sha256"],
                    pramana=Pramana(cl["pramana"]),
                    backing_call_id=cl.get("backing_call_id"),
                    cot_trace_sha256=cl.get("cot_trace_sha256"),
                )
                for cl in data["claims"]
            ),
            issued_at=datetime.fromisoformat(data["issued_at"]),
            tag_hex=data["tag_hex"],
        )
        return verify_receipt(receipt)
    except (ValueError, KeyError, RuntimeError) as exc:
        _logger.warning("ZKPROV: receipt parse failure: %s", exc)
        return False
